### ISSUE TITLE
hunter AimedShot MultiShot castbar not show

### ISSUE THREAD

**Issue by JSZMonkey** [AzeriteTeam/AzeriteUI_Classic#15] opened 2019-09-19 16:42 UTC
hunter AimedShot MultiShot castbar not show
target castbar not show
target debuff Remaining time not show

**Comment by goldpaw** [comment] 2019-09-19 16:58
None of these are bugs. We list on the download and description pages here, on Curse and Twitch that the pet bar isn't there yet. 

And target castbars and target debuff time not showing, that's a limitation in Classic. The default blizzard UI doesn't show it either. 

We're adding a pet bar, and will add debuff durations for at least our own debuffs at some point, but this is still not a bug, so closing this.

**Closed by goldpaw** 2019-09-19 16:58 UTC
Labels: bug
